EyeForEvents/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('user/', include('user.urls')),
    path('events/', include('events.urls')),
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #Static media urls

events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.newEvent, name='create'),
    path('CreateEvent', views.create_event, name='create_event'), #Store event details to db
    # Ex - /events/EventRegistered
    path('EventRegistered',views.successFull,name="event_created_successfully"),
    #Example - /events/5
    path('<uuid:event_id>/', views.detail, name='detail'),
    path('<uuid:event_id>/Register', views.registerForEvent, name='Register'),
]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    ##Remove me later
    path('debug/',views.debug,name="debug"),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
#UserCreationForm to create users
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

#create signup form with extra field
class SignUpForm(UserCreationForm):

    #creating email field,required,widget used to represent html element
    email = forms.EmailField(label="",widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}),)
    
    #creating 1st name field max length= 100 char,required
    first_name = forms.CharField(label="",widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}),)

    #creating last name field max length= 100 char,required
    last_name = forms.CharField(label="",widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),)
    
    #function to prevent duplicate email
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email
    
    #function for checking empty password & if pass1 = pass2 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    #creating form with extra fields 
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)

    #*args for any no of args **kwargs for dictionary args
    def __init__(self, *args, **kwargs):
	    super(SignUpForm, self).__init__(*args, **kwargs)

	    self.fields['password1'].widget.attrs['class'] = 'form-control'
	    self.fields['password1'].widget.attrs['placeholder'] = 'Password'
	    self.fields['password1'].label = ''
	    self.fields['password1'].help_text = '<ul class="form-text text-muted small" style="text-align:left;"><li>Your password must contain at least 8 characters.</li></ul>'

	    self.fields['password2'].widget.attrs['class'] = 'form-control'
	    self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
	    self.fields['password2'].label = ''
	    self.fields['password2'].help_text = '<span class="form-text text-muted" style="text-align:left;"><small>Enter the same password as before, for verification.</small></span>'
  

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib import messages
from .forms import SignUpForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

#If Not Authenticated show user a path to authenticate i.e. login or register option
#Check whether the user is authenticated if not send user to get authentication
@login_required(login_url='/user/login/')
def home(request):
    return redirect("profile")

#profile page request
@login_required(login_url='/user/login/')
def profile(request):
    return render(request,"user/profile.html")

def login_user(request):
    if request.method == "POST":
        # if someone fills out form , Post it
        username = request.POST["email"]
        password = request.POST["password"]

        #authenticate takes username and password for the cuurent case, checks them against each authentication backend
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # if user exist
            login(request, user)
            messages.success(request, ("You're logged in!!"))
            return redirect("profile")
            # routes to 'profile' on successful login
        else:
            messages.success(request, ("Error logging in!!"))
            return redirect("login")
            # re routes to login page upon unsucessful login
    else:
        return render(request, "user/login.html", {})


def logout_user(request):
    logout(request)
    messages.success(request, ("Youre now logged out"))
    return redirect("home")

#to view register form 
def register(request):
    #request that makes changes in the database - should use POST, in this pass won't come in url
    if request.method == 'POST':
        #creates register form 
        form = SignUpForm(request.POST)
        if form.is_valid():

            #setting email as username
            username = form.cleaned_data['email']
            password = form.cleaned_data['password1']

            #create user , set username & email both as email
            user = User.objects.create_user(username,username,password)

            #store first_name & last_name for profile.html
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']

            #save the user
            user.save()

            #login
            login(request,user)

            #show register msg & redirect to profile
            messages.success(request, ('Youre now registered'))
            return redirect('profile')
    else:
                form = SignUpForm() 
    context = {'form': form}
    return render(request, 'user/register.html', context)


##REMove me later
def debug(request):
    return render(request,'user/debug.html',{'msg':str(request.user)})

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
      href = "stylecss.css"
    />

    <title>EyeForEvents</title>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark bg-dark"
    >
      <a class="navbar-brand text-white" href="../../events">EyeForEvents</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <!--to know if user is logged in or not-->
          {% if user.is_authenticated %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          <!--View user's profile-->

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'profile' %}">View Profile</a>
          </li>

          <!--Login block-->
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

          <!--Register block-->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif%}
        </ul>
      </div>
    </nav>
    <br />

    <div class="container">
      {% if messages %} {% for message in messages %}
      <div class="alert alert-danger alart-dismissable" role="alert">
        <button class="close" data-dismiss="alert">
          <small><sup>x</sup></small>
        </button>
        {{ message }}
      </div>
      {% endfor%} {% endif %} {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

user/templates/user/debug.html
{{ msg }}

user/templates/user/home.html
{% extends 'user/base.html' %} {% block content %}

<h1>Home page</h1>

{% endif %} {% endblock %}

user/templates/user/login.html
{% extends 'user/base.html' %} {% block content %} {% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<div
  class="border bg-light border-dark my-4 pb-4"
  style="background-color: #b3ecff"
>
  <div class="bg-info">
    <h2 class="text-center text-white" style="background: #004d66">LOGIN</h2>
  </div>
  <br />
  <div class="col-md-6 offset-md-3 pt-5 pb-4" style="background-color: #b3ecff">
    <!--takes to login page using POST-->

    <form method="POST" action="{% url 'login' %}">
      {% csrf_token %}

      <div class="form-group">
        <input
          type="text"
          class="form-control"
          placeholder="Enter your Email"
          name="email"
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          class="form-control"
          placeholder="Enter Password"
          name="password"
        />
      </div>

      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>

{% endblock %}

user/templates/user/profile.html
{% extends 'user/base.html' %} {% block content %}

<!--showing user's profile-->
{% if user.is_authenticated %}

<style>
  .bg {
    animation: slide 3s ease-in-out infinite alternate;
    background-image: linear-gradient(-60deg, #6c3 50%, #09f 50%);
    bottom: 0;
    left: -50%;
    opacity: 0.5;
    position: fixed;
    right: -50%;
    top: 0;
    z-index: -1;
  }

  .bg2 {
    animation-direction: alternate-reverse;
    animation-duration: 4s;
  }

  .bg3 {
    animation-duration: 5s;
  }

  .content {
    background-color: rgba(255, 255, 255, 0.8);
    border-radius: 0.5em;
    box-shadow: 0 0 0.25em rgba(0, 0, 0, 0.25);
    box-sizing: border-box;
    left: 50%;
    padding: 3vmin;
    position:fixed;
    width: 50%;
    text-align: center;
    top: 60%;
    transform: translate(-50%, -50%);
  }

  h1 {
    font-family: monospace;
  }

  @keyframes slide {
    0% {
      transform: translateX(-25%);
    }
    100% {
      transform: translateX(25%);
    }
  }
</style>

<div class="bg"></div>
<div class="bg bg2"></div>
<center><h5>{{ msg }}</h5></center>
<div style="display:block;">
  <h1>
    Hey {{user.first_name}} !!<br />
    Welcome to EyeForEvents
  </h1>
</div>
<br>
<div class="bg bg3"></div>
<br>
<div class="content">
<h4 class="text-primary">Personal details</h4>
<h6>Name: {{user.first_name}} {{ user.last_name}}<h6>
        <h6>Email: {{user.email}}</h6>

<h4 class="text-primary pt-2">Registered Event:</h4>
{% if user.participated_in %}
    <ul>
    {% for event in user.participated_in.all %}
        <li><a href="{% url 'events:detail' event.id %}">{{ event.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Event Available.</p>
{% endif %}


<h4 class="text-primary">Events By You:</h4>
{% if user.created_by.all %}
    <ul>
    {% for event in user.created_by.all %}
        <li><a href="{% url 'events:detail' event.id %}">{{ event.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Event Available.</p>
{% endif %}
</div>
{% endif%}
{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %} {% block content %} {% load static %}
<div
  class="border border-dark my-4 pb-4"
  style="background: #b3ecff; background: (#b3ecff, 0.5)"
>
  <div class="bg-info">
    <h2 class="text-center text-white fs-2" style="background-color: #004d66">
      REGISTER
    </h2>
  </div>

  <div class="col-md-6 offset-md-3 pt-5 pb-4" style="opacity: default">
    <!--in register page when POST -->
    <form
      method="POST"
      action="{% url 'register' %}"
      style="font-weight: bold; color: #000000"
    >
      {% csrf_token %} {% if form.errors %}
      <div class="alert alert-danger alart-dismissable" role="alert">
        <button class="close" data-dismiss="alert">
          <small><sup>x</sup></small>
        </button>

        {% for field in form%} {% if field.errors%} {{field.errors}} {% endif%}
        {% endfor %}
      </div>

      {% endif %}

      <!--Form created as SignUpForm is displayed here-->
      {{ form.as_p }}

      <input type="submit" value="Register" class="btn btn-primary" />
    </form>
  </div>
</div>
{% endblock %}